# Generated by Django 4.0.3 on 2022-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_order_date_cart_ordered_cart_product_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
